[font]
size = 16

[font.normal]
family = "Scientifica"
style = "Regular"

[scrolling]
history = 10000

[window]
opacity = 0.95
title = "Alacritty"

[window.padding]
x = 9
y = 9

# BEGIN WAL
[colors.primary]
background = '#010615'
foreground = '#cad1de'

[colors.cursor]
text   = '#010615' # Apply background color to color of text inside cursor
cursor = '#cad1de' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#010615' # Same as above
cursor  = '#cad1de'

[colors.search.matches]
foreground = '#010615' # Same as above
background = '#cad1de' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#8d929b'
background = '#cad1de'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#010615'
red     = '#0C33E2'
green   = '#144EF9'
yellow  = '#1C5EF2'
blue    = '#2E6EFC'
magenta = '#288EFC'
cyan    = '#6091D1'
white   = '#cad1de'

[colors.bright]
black   = '#8d929b'
red     = '#0C33E2'
green   = '#144EF9'
yellow  = '#1C5EF2'
blue    = '#2E6EFC'
magenta = '#288EFC'
cyan    = '#6091D1'
white   = '#cad1de'
# END WAL
