preload = /home/pedro/git/T480-rice/wallpapers/two_fishes.jpg
preload = /home/pedro/git/T480-rice/wallpapers/hollow_knight_minimal.jpg
preload = /home/pedro/git/T480-rice/wallpapers/japan.jpg
preload = /home/pedro/git/T480-rice/wallpapers/eclipse.jpg
wallpaper = eDP-1, /home/pedro/git/T480-rice/wallpapers/two_fishes.jpg
